import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import transcript from './fixtures/original-transcript.jsonl?raw';
import { parseJsonl } from './parser/parseJsonl';
import { normalizeEvent } from './parser/normalizeEvent';
import { buildSessionState } from './lifecycle/session';
import { initialPlayback, advancePlayback } from './lifecycle/recovery';
import { rescueSteps } from './lifecycle/events';
import { createCheckpointContext } from './checkpoint/checkpointContext';
import './styles.css';

type Page = 'Overview'|'Rescue'|'Context'|'Graph'|'Tests'|'Checkpoints'|'Sessions';
const nav: Page[] = ['Overview','Rescue','Context','Graph','Tests','Checkpoints','Sessions'];
const parsed = parseJsonl(transcript); const session = buildSessionState(parsed.records.map(normalizeEvent));
function Badge({children, tone='muted'}:{children:React.ReactNode;tone?:string}) { return <span className={`badge ${tone}`}>{children}</span> }
function App() { const [page,setPage]=useState<Page>('Overview'); const [playback,setPlayback]=useState(()=>initialPlayback(session)); const [error,setError]=useState<string | undefined>(parsed.errors[0]); const running=playback.status==='running'; useEffect(()=>{ if(!running) return; const timer=window.setTimeout(()=>setPlayback(p=>advancePlayback(p,rescueSteps.length)),680); return()=>clearTimeout(timer); },[running,playback.visibleSteps]); const start=()=>{setError(undefined);setPlayback({status:'running',visibleSteps:0,session});}; const replay=()=>{setPlayback({status:'running',visibleSteps:0,session});}; const context=useMemo(()=>createCheckpointContext(session),[]); const visible=playback.visibleSteps; const isDone=playback.status==='complete'; return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">⌁</span><span>CODE RESCUE</span></div><nav>{nav.map(item=><button className={page===item?'active':''} onClick={()=>setPage(item)} key={item}><span>{item==='Overview'?'⌘':item==='Rescue'?'↯':item==='Context'?'◫':item==='Graph'?'⌇':item==='Tests'?'✓':item==='Checkpoints'?'◇':'◌'}</span>{item}</button>)}</nav><div className="side-note"><span className="dot live"/> Simulation ready<br/><small>Original JSONL source</small></div></aside><main><header><div className="crumb">WORKSPACE / {page.toUpperCase()}</div><div className="header-actions"><Badge tone="live"><span className="dot live"/> LIVE</Badge><button className="icon">⚙</button><div className="avatar">SR</div></div></header><AnimatePresence mode="wait"><motion.section key={page} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.18}}>{error ? <div className="error"><b>Transcript issue</b><span>{error}</span><button onClick={()=>setError(undefined)}>Dismiss</button></div>: null}{page==='Overview'&&<Overview visible={visible} start={start} replay={replay} done={isDone}/>} {page==='Rescue'&&<Rescue visible={visible} start={start} replay={replay} done={isDone}/>} {page==='Context'&&<Context context={context}/>} {page==='Graph'&&<Graph/>} {page==='Tests'&&<Tests done={isDone}/>} {page==='Checkpoints'&&<Checkpoints done={isDone}/>} {page==='Sessions'&&<Sessions/>}</motion.section></AnimatePresence></main></div> }
function Title({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="page-title"><p>{eyebrow}</p><h1>{title}</h1><span>{sub}</span></div>}
function Metrics(){const items=[['01','Active incidents'],['18','Resolved incidents'],['8 / 8','Tests passing'],['01','Checkpoints']];return <div className="metrics">{items.map(([n,l])=><div className="metric" key={l}><b>{n}</b><span>{l}</span></div>)}</div>}
function Incident(){return <div className="incident panel"><div className="panel-label">ACTIVE INCIDENT <Badge tone="warning">RESOLVING</Badge></div><h2>Coupon validation failure <span>#CR-1042</span></h2><div className="facts"><div><label>Repository</label>checkout-service</div><div><label>Branch</label>feature/add-coupon-validation</div><div><label>Agent</label>AcmeCode 1.4.2</div></div></div>}
function Timeline({visible}:{visible:number}){return <div className="timeline">{rescueSteps.map((step,i)=>{const active=i<visible;const current=i===visible&&visible<rescueSteps.length;return <motion.div className={`timeline-row ${active?'success':''} ${current?'current':''}`} key={step.title} initial={{opacity:0}} animate={{opacity: i<=visible?1:.38}}><div className="rail"><span>{active?'✓':current?'•':'·'}</span>{i<rescueSteps.length-1&&<i/>}</div><div><div className="time">09:42:{String(i+1).padStart(2,'0')} {current&&<Badge tone="live">RUNNING</Badge>}</div><b>{step.title}</b><p>{step.description}</p></div></motion.div>})}</div>}
function Rescue({visible,start,replay,done}:{visible:number;start:()=>void;replay:()=>void;done:boolean}){return <><Title eyebrow="LIVE RECOVERY" title="Rescue timeline" sub="Deterministic playback reconstructed from the original agent transcript."/><div className="split"><div className="panel rescue-panel"><div className="panel-head"><div><div className="panel-label">LIVE RESCUE <Badge tone="muted">SIMULATED PLAYBACK</Badge></div><h2>{done?'Recovery verified':'Awaiting rescue operation'}</h2></div><div className="controls"><button className="primary" onClick={start}>{visible?'RESTART':'START RESCUE'}</button>{visible>0&&<button className="secondary" onClick={replay}>REPLAY</button>}</div></div><Timeline visible={visible}/></div><Incident/></div></>}
function Overview({visible,start,replay,done}:{visible:number;start:()=>void;replay:()=>void;done:boolean}){return <><Title eyebrow="CODE RESCUE" title="Autonomous recovery for broken software." sub="Preserving the reasoning behind every repair."/><div className="system"><span className="dot live"/> RESCUE ENGINE ONLINE <em>JSONL reconstruction active</em></div><Metrics/><div className="overview-grid"><Incident/><div className="panel live-panel"><div className="panel-head"><div><div className="panel-label">LIVE RESCUE <Badge tone="muted">SIMULATED</Badge></div><h2>{done?'Recovery verified':visible?'Recovering safely':'Ready to reconstruct'}</h2></div><button className="primary" onClick={visible?replay:start}>{visible?'REPLAY':'START RESCUE'}</button></div>{visible===0?<div className="empty">Start the replay to trace the recovery from incident through a preserved checkpoint.</div>:<Timeline visible={visible}/>}</div></div></>}
function Context({context}:{context:ReturnType<typeof createCheckpointContext>}){return <><Title eyebrow="CHECKPOINT CONTEXT" title="Recovered reasoning" sub="What the next agent needs to continue safely."/><div className="context-grid">{[['Recovered intent',context.intent],['Previous work','Coupon validation implemented\nTests added\nInitial test failure discovered\nValidation order corrected\nFinal tests passed'],['Decision',context.decisions[0]],['Failure',context.failures[0]],['Verification',context.tests],['Open questions','None.']].map(([k,v])=><article className="panel context-card" key={k}><div className="panel-label">{k}</div><p>{v}</p></article>)}</div></>}
function Graph(){return <><Title eyebrow="ENTIRE GRAPH" title="Impact analysis" sub="Dependency intelligence becomes available during an active recovery workflow."/><div className="graph panel"><div className="network"><span/><span/><span/><span/><span/></div><div><Badge>GRAPH ANALYSIS</Badge><h2>Waiting for an active rescue operation.</h2><p>Impact analysis will appear here during the recovery workflow.</p></div></div></>}
function Tests({done}:{done:boolean}){const test=done?'8 / 8 PASS':'0 / 0';return <><Title eyebrow="VERIFICATION" title="Test status" sub="Results are updated from session state during rescue playback."/><div className="test-grid">{[['Targeted tests',test,done?'success':'waiting'],['Regression tests',done?'PASS':'0 / 0',done?'success':'waiting'],['Overall',done?'VERIFIED':'WAITING',done?'success':'waiting']].map(([t,v,c])=><div className="panel test-card" key={t}><div className="panel-label">{t}</div><b className={c}>{v}</b><span>{done?'Transcript-derived verification':'Start rescue to populate results'}</span></div>)}</div></>}
function Checkpoints({done}:{done:boolean}){return <><Title eyebrow="ENTIRE CHECKPOINTS" title="Continuity, preserved" sub="Checkpoints capture the intent and evidence behind a safe recovery."/><div className="checkpoint panel">{[['INITIAL UNDERSTANDING','Project architecture established.'],['PRE-CURVEBALL STABLE STATE','Not created yet'],['CURVEBALL RESPONSE','Not created yet'],['FINAL IMPLEMENTATION',done?'Recovery checkpoint created in demo state.':'Not created yet']].map(([a,b],i)=><div className="checkpoint-row" key={a}><span>{i+1}</span><div><b>{a}</b><p>{b}</p></div></div>)}</div></>}
function Sessions(){return <><Title eyebrow="SESSION HISTORY" title="One recovery session" sub="Phase 1 retains the current transcript session only."/><div className="panel session"><div><div className="panel-label">SESSION</div><h2>btw-track3-demo-001</h2></div><Badge tone="success">COMPLETED</Badge><dl><dt>Agent</dt><dd>AcmeCode 1.4.2</dd><dt>Repository</dt><dd>checkout-service</dd><dt>Branch</dt><dd>feature/add-coupon-validation</dd></dl></div></>}
createRoot(document.getElementById('root')!).render(<App/>);
